cocur_slugify:
    lowercase: false # or true
    separator: '-' # any string
    # regexp: <string>
    rulesets: ['austrian'] # List of rulesets: https://github.com/cocur/slugify/tree/master/Resources/rules